public enum Genero
{
Acao = 1,
Aventura = 2,
Cinema_de_arte = 3,
Chanchada = 4,
Comedia = 5,
Comédia_de_acao = 6,
Comedia_de_terror = 7,
Comedia_dramatica = 8,
Comedia_romântica = 9,
Danca = 10,
Documentario = 11,
Docuficcao = 12,
Drama = 13,
Espionagem = 14,
Faroeste =15,
Fantasia = 16,
Fantasia_cientifica = 17,
Ficcao_cientifica = 18,
Filmes_com_truques = 19,
Filmes_de_guerra = 20,
Misterio = 21,
Musical = 22,
Filme_policial = 23,
Romance = 24,
Terror = 25,
Thriller = 26
}